'use strict';
/**
 * Client example application
 */

const UIAMPClient = require('../index.js'); // this is require('uiamp-client');

let clientObj = new UIAMPClient({
  url: 'http://localhost:6801',
  key: 'YOUR_UIAMP_KEY' // UIAMP key, generated by running "npm run token" in the uiamp-server application.
});


clientObj.on('connect', () => {
  let accessId = 'accessId',
    roleId = 'roleId',
    userId = '1';

  return clientObj.verify(accessId, {
    user_id: userId,
    category: 'my.category',
    action: ['READ', 'UPDATE']
  }).then((res) => {
    console.log("Verify: ", res);
    return clientObj.grantPermission(accessId, {
      create: true,
      update: false,
      delete: true,
      role: 'owner',
      category: 'my.category',
      user_id: '2',
      //entity_id: '123456771',
      //entity_type: 'vehicle'
    });
  }).then((res) => {
    console.log("Granted", res);
    return clientObj.revokePermission(accessId, {
      role: 'owner',
      category: 'dash.sales',
      user_id: '2',
      //entity_id: '123456771',
      entity_type: 'vehicle'
    });
  }).then((res) => {
    console.log("Revoked", res);
    return clientObj.grantAccess(accessId, {
      user_id: userId,
      role_id: roleId
    })
  }).then((res) => {
    console.log('User Granted:', res.result);
    return clientObj.revokeAccess(accessId, {
      user_id: userId,
      role_id: roleId
    });
  }).then((res) => {
    console.log('User Revoked:', res.result);
  }).catch((e) => {
    console.log(e);
  });
});

clientObj.connect();
